// <auto-generated />
using System;
using Ara.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ara.Api.Migrations
{
    [DbContext(typeof(ARADbContext))]
    [Migration("20260530074402_AddVolunteerStays")]
    partial class AddVolunteerStays
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ara.Domain.Models.Animal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("AnimalStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Breed")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CatZone")
                        .HasColumnType("text");

                    b.Property<string>("DogZone")
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("HandlingFlags")
                        .HasColumnType("integer");

                    b.Property<string>("HandlingLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HandlingNotes")
                        .HasColumnType("text");

                    b.Property<string>("History")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("InTreatment")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Picture")
                        .HasColumnType("text");

                    b.Property<bool>("RequiresCare")
                        .HasColumnType("boolean");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Animals");
                });

            modelBuilder.Entity("Ara.Domain.Models.Information.InformationBlob", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Key");

                    b.ToTable("InformationBlobs");
                });

            modelBuilder.Entity("Ara.Domain.Models.ShiftInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ShiftTemplateId")
                        .HasColumnType("uuid");

                    b.Property<string>("ShiftType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ShiftTemplateId");

                    b.HasIndex("Date", "ShiftType")
                        .IsUnique();

                    b.ToTable("ShiftInstances");
                });

            modelBuilder.Entity("Ara.Domain.Models.ShiftTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShiftType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ShiftType", "Season")
                        .IsUnique();

                    b.ToTable("ShiftTemplates");
                });

            modelBuilder.Entity("Ara.Domain.Models.TaskAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TaskInstanceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VolunteerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VolunteerId");

                    b.HasIndex("TaskInstanceId", "VolunteerId")
                        .IsUnique();

                    b.ToTable("TaskAssignments");
                });

            modelBuilder.Entity("Ara.Domain.Models.TaskInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CompletedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int?>("MaxVolunteers")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("RequiredVolunteers")
                        .HasColumnType("integer");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<Guid>("ShiftInstanceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TaskTemplateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CompletedByUserId");

                    b.HasIndex("ShiftInstanceId");

                    b.HasIndex("TaskTemplateId");

                    b.ToTable("TaskInstances");
                });

            modelBuilder.Entity("Ara.Domain.Models.TaskTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("MaxVolunteers")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("RequiredVolunteers")
                        .HasColumnType("integer");

                    b.Property<Guid>("ShiftTemplateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ShiftTemplateId");

                    b.ToTable("TaskTemplates");
                });

            modelBuilder.Entity("Ara.Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenCreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RefreshTokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RefreshTokenHash")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("RefreshTokenRevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Volunteer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Pending");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("VolunteerFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("VolunteerTo")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Ara.Domain.Models.VolunteerStay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Pending");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("VolunteerFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly>("VolunteerTo")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Status", "VolunteerFrom", "VolunteerTo");

                    b.ToTable("VolunteerStays");
                });

            modelBuilder.Entity("Ara.Domain.Models.ShiftInstance", b =>
                {
                    b.HasOne("Ara.Domain.Models.ShiftTemplate", "ShiftTemplate")
                        .WithMany()
                        .HasForeignKey("ShiftTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShiftTemplate");
                });

            modelBuilder.Entity("Ara.Domain.Models.TaskAssignment", b =>
                {
                    b.HasOne("Ara.Domain.Models.TaskInstance", "TaskInstance")
                        .WithMany("Assignments")
                        .HasForeignKey("TaskInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ara.Domain.Models.User", "Volunteer")
                        .WithMany()
                        .HasForeignKey("VolunteerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TaskInstance");

                    b.Navigation("Volunteer");
                });

            modelBuilder.Entity("Ara.Domain.Models.TaskInstance", b =>
                {
                    b.HasOne("Ara.Domain.Models.User", "CompletedByUser")
                        .WithMany()
                        .HasForeignKey("CompletedByUserId");

                    b.HasOne("Ara.Domain.Models.ShiftInstance", "ShiftInstance")
                        .WithMany("Tasks")
                        .HasForeignKey("ShiftInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ara.Domain.Models.TaskTemplate", "TaskTemplate")
                        .WithMany()
                        .HasForeignKey("TaskTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompletedByUser");

                    b.Navigation("ShiftInstance");

                    b.Navigation("TaskTemplate");
                });

            modelBuilder.Entity("Ara.Domain.Models.TaskTemplate", b =>
                {
                    b.HasOne("Ara.Domain.Models.ShiftTemplate", "ShiftTemplate")
                        .WithMany("Tasks")
                        .HasForeignKey("ShiftTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShiftTemplate");
                });

            modelBuilder.Entity("Ara.Domain.Models.VolunteerStay", b =>
                {
                    b.HasOne("Ara.Domain.Models.User", "User")
                        .WithMany("VolunteerStays")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ara.Domain.Models.ShiftInstance", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Ara.Domain.Models.ShiftTemplate", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Ara.Domain.Models.TaskInstance", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("Ara.Domain.Models.User", b =>
                {
                    b.Navigation("VolunteerStays");
                });
#pragma warning restore 612, 618
        }
    }
}
